name: BlackListIPs
version: 1.0
main: com.javanameconvention.blacklistips.Main
api-version: 1.14
description: Plugin to disable some access hostnames (if you have a domain, and don't want users connecting through public ip)
