maxSpawnAmount: 100
defaults:
  enabled: true
  power: 2
  setFire: false
  breakBlocks: true
  triggeredByAny: false
# mobs:
#   Cow:
#     enabled: false
#   Sheep:
#     power: 10
#     setFire: false